import { test, expect } from '@playwright/test';

test('production ZIP installs on MariaDB, locks setup, and auto-submits a real timed session', async ({ browser }) => {
    test.skip(!process.env.EP_INSTALLER_URL, 'Run explicitly against a disposable uninstalled release.');
    test.setTimeout(180000);
    const baseURL = process.env.EP_INSTALLER_URL;
    const adminContext = await browser.newContext({ baseURL });
    const page = await adminContext.newPage();
    await page.goto('/setup.php');
    await expect(page.locator('h1')).toHaveText('Pasang ExamPractice');
    await page.locator('[name="setup_code"]').fill('incorrect-code');
    await page.getByRole('button', { name: 'Buka pemasangan' }).click();
    await expect(page.locator('.alert')).toContainText('Kode pemasangan tidak sesuai');
    await page.locator('[name="setup_code"]').fill(process.env.EP_SETUP_CODE);
    await page.getByRole('button', { name: 'Buka pemasangan' }).click();
    await expect(page.locator('summary')).toContainText('Persyaratan server terpenuhi');
    const values = { app_url: baseURL, db_host: '127.0.0.1', db_port: process.env.EP_DB_PORT || '3311', db_database: process.env.EP_DB_NAME || 'exampractice_install_test', db_username: 'root', db_password: process.env.EP_DB_PASSWORD, name: 'Production QA Admin', username: 'qa-admin', email: 'qa@example.invalid', password: 'InstallerTest2026!', password_confirmation: 'InstallerTest2026!' };
    for (const [field, value] of Object.entries(values)) await page.locator(`[name="${field}"]`).fill(value);
    await page.screenshot({ path: 'storage/app/qa-screenshots/13-hostinger-installer.png', fullPage: true });
    await page.getByRole('button', { name: 'Pasang sistem', exact: true }).click();
    await expect(page.locator('h1')).toHaveText('Sistem berhasil dipasang', { timeout: 45000 });
    await page.screenshot({ path: 'storage/app/qa-screenshots/14-installation-complete.png', fullPage: true });
    await page.getByRole('link', { name: 'Buka halaman login' }).click();
    await page.locator('[name="username"]').fill('qa-admin');
    await page.locator('[name="password"]').fill('InstallerTest2026!');
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(page).toHaveURL(`${baseURL}/dashboard`);
    await expect(page.locator('main')).toContainText('Japanese Language Practice');
    expect((await page.request.get('/setup.php')).status()).toBe(404);
    expect((await page.request.get('/.env')).status()).toBe(404);
    expect((await page.request.get('/exampractice/.env')).status()).toBe(404);
    await page.goto('/admin/students');
    await expect(page.locator('tbody')).not.toContainText('STU-001');
    await page.goto('/admin/students/create');
    await page.locator('[name="name"]').fill('Production QA Student');
    await page.locator('[name="username"]').fill('QA-STUDENT');
    await page.locator('[name="password"]').fill('ProductionStudent2026!');
    await page.getByRole('button', { name: 'Save changes', exact: true }).click();
    await expect(page.locator('.alert.success')).toContainText('Student created');
    await page.locator('input[value="program:1"]').check();
    await page.getByRole('button', { name: 'Save access', exact: true }).click();
    await expect(page.locator('.alert.success')).toContainText('Learning access updated');
    await page.goto('/admin/content/packages/create');
    await page.locator('[name="module_id"]').selectOption('1');
    await page.locator('[name="title"]').fill('QA one-minute timer');
    await page.locator('[name="duration_minutes"]').fill('1');
    await page.locator('[name="status"]').selectOption('active');
    await page.getByRole('button', { name: 'Save changes', exact: true }).click();
    await expect(page.locator('.alert.success')).toContainText('Changes saved');
    const packageId = new URL(page.url()).pathname.match(/packages\/(\d+)\/edit/)[1];
    await page.goto('/admin/content/questions/create');
    await page.locator('[name="practice_package_id"]').selectOption(packageId);
    await page.locator('[name="question"]').fill('Choose the saved answer.');
    for (const [letter, text] of [['a', 'Correct'], ['b', 'Incorrect B'], ['c', 'Incorrect C'], ['d', 'Incorrect D']]) await page.locator(`[name="option_${letter}"]`).fill(text);
    await page.locator('[name="correct_answer"]').selectOption('A');
    await page.locator('[name="status"]').selectOption('active');
    await page.getByRole('button', { name: 'Save changes', exact: true }).click();
    await expect(page.locator('.alert.success')).toContainText('Changes saved');
    const studentContext = await browser.newContext({ baseURL, viewport: { width: 390, height: 844 } });
    const studentPage = await studentContext.newPage();
    await studentPage.goto('/login');
    await studentPage.locator('[name="username"]').fill('QA-STUDENT');
    await studentPage.locator('[name="password"]').fill('ProductionStudent2026!');
    await studentPage.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(studentPage).toHaveURL(`${baseURL}/dashboard`);
    await studentPage.goto(`/packages/${packageId}`);
    await studentPage.locator('form[action$="/start"] button').click();
    await expect(studentPage).toHaveURL(/\/practice\/\d+$/);
    await studentPage.locator('input[value="A"]').check();
    await expect(studentPage.getByText('All answers saved', { exact: true })).toBeVisible();
    await expect(studentPage).toHaveURL(/\/results\/\d+$/, { timeout: 75000 });
    await expect(studentPage.locator('.result-summary')).toContainText('100');
    await expect(studentPage.locator('.alert.info')).toContainText('saved answers were submitted automatically');
    await studentPage.screenshot({ path: 'storage/app/qa-screenshots/15-timer-auto-submit.png', fullPage: true });
    await page.goto(`/admin/results?program=1&module=1&package=${packageId}`);
    await expect(page.locator('tbody')).toContainText('QA-STUDENT');
    await expect(page.locator('tbody')).toContainText('100%');
    await adminContext.close();
    await studentContext.close();
});
