@extends('layouts.app')
@section('title',__('ui.dashboard'))
@section('content')
<x-page-heading :title="__('ui.dashboard')" :subtitle="__('ui.admin_subtitle')"><a class="button primary" href="{{ route('admin.content.create','questions') }}"><i data-lucide="plus"></i>{{ __('ui.add_question') }}</a></x-page-heading>
<div class="stats-grid"><x-stat :label="__('ui.total_students')" :value="$students" icon="users"/><x-stat :label="__('ui.total_questions')" :value="$questions" icon="circle-help" tone="green"/><x-stat :label="__('ui.completed_practices')" :value="$completed" icon="clipboard-check" tone="amber"/><x-stat :label="__('ui.average_score')" :value="$average" suffix="%" icon="chart-no-axes-combined" tone="rose"/></div>
<section class="section"><div class="section-heading"><h2>{{ __('ui.quick_actions') }}</h2></div><div class="quick-actions">@foreach([['admin.content.create','questions','circle-help','add_question','blue'],['admin.content.create','materials','book-open-text','add_material','green'],['admin.students.create',null,'user-plus','add_student','rose'],['admin.import',null,'upload','import','amber']] as [$route,$param,$icon,$label,$tone])<a class="quick-action" href="{{ route($route,$param) }}"><span class="item-icon {{ $tone }}"><i data-lucide="{{ $icon }}"></i></span><strong>{{ __('ui.'.$label) }}</strong><i data-lucide="arrow-up-right"></i></a>@endforeach</div></section>
<section class="section"><div class="section-heading"><h2>{{ __('ui.programs') }}</h2><a class="text-link" href="{{ route('admin.content.index','programs') }}">{{ __('ui.view_all') }}<i data-lucide="arrow-right"></i></a></div><div class="admin-programs">@forelse($programs as $program)<a class="admin-program" href="{{ route('admin.content.edit',['programs',$program->id]) }}"><img src="{{ asset('images/'.$program->cover.'.jpg') }}" alt="{{ $program->title }}"><div><strong>{{ $program->title }}</strong><small>{{ $program->modules_count }} {{ __('ui.modules') }}</small></div><x-status :status="$program->status"/><i data-lucide="chevron-right"></i></a>@empty<x-empty/>@endforelse</div></section>
<section class="section"><div class="section-heading"><h2>{{ __('ui.recent_results') }}</h2><a class="text-link" href="{{ route('admin.results') }}">{{ __('ui.view_all') }}<i data-lucide="arrow-right"></i></a></div><x-attempt-table :attempts="$recent" :admin="true"/></section>
@endsection
