@extends('layouts.app')
@section('title',__('ui.dashboard'))
@section('content')
<x-page-heading :title="__('ui.welcome',['name'=>explode(' ',auth()->user()->name)[0]])" :subtitle="__('ui.dashboard_subtitle')"><span class="date-label"><i data-lucide="calendar-days"></i>{{ now()->format('d M Y') }}</span></x-page-heading>
<div class="stats-grid"><x-stat :label="__('ui.enrolled_programs')" :value="$programs->count()" icon="library-big"/><x-stat :label="__('ui.completed_practices')" :value="$history->count()" icon="circle-check" tone="green"/><x-stat :label="__('ui.average_score')" :value="round($history->avg('score')??0)" suffix="%" icon="chart-no-axes-combined" tone="amber"/><x-stat :label="__('ui.practice_time')" :value="intdiv($history->sum(fn($a)=>$a->durationSeconds()),60)" :suffix="__('ui.min')" icon="clock-3" tone="rose"/></div>
@foreach($ongoing as $attempt)<div class="resume-banner"><div><i data-lucide="timer"></i><strong>{{ $attempt->snapshot['title'] }}</strong></div><a class="button primary compact" href="{{ route('practice.show',$attempt) }}">{{ __('ui.resume') }}<i data-lucide="arrow-right"></i></a></div>@endforeach
<section class="section"><div class="section-heading"><h2>{{ __('ui.available_programs') }}</h2><a class="text-link" href="{{ route('programs') }}">{{ __('ui.view_all') }}<i data-lucide="arrow-right"></i></a></div><div class="program-grid">@forelse($programs->take(3) as $program)<x-program-card :program="$program" :module-count="$packages->filter(fn($p)=>$p->module->program_id===$program->id)->pluck('module_id')->merge($materials->filter(fn($m)=>$m->module->program_id===$program->id)->pluck('module_id'))->unique()->count()"/>@empty<x-empty :text="__('ui.no_access')"/>@endforelse</div></section>
<div class="dashboard-columns"><section class="section"><div class="section-heading"><h2>{{ __('ui.continue_learning') }}</h2></div><div class="item-list">@forelse($packages->take(3) as $package)<x-package-row :package="$package"/>@empty<x-empty/>@endforelse</div></section><section class="section"><div class="section-heading"><h2>{{ __('ui.materials') }}</h2><a class="text-link" href="{{ route('materials') }}">{{ __('ui.view_all') }}</a></div>@forelse($materials->take(3) as $material)<a class="material-link" href="{{ route('materials.show',$material) }}"><span class="item-icon green"><i data-lucide="book-open-text"></i></span><div><strong>{{ $material->title }}</strong><small>{{ $material->reading_minutes }} {{ __('ui.min') }} · {{ $material->module->title }}</small></div><i data-lucide="chevron-right"></i></a>@empty<x-empty/>@endforelse</section></div>
<section class="section"><div class="section-heading"><h2>{{ __('ui.recent_activity') }}</h2><a class="text-link" href="{{ route('history') }}">{{ __('ui.view_all') }}<i data-lucide="arrow-right"></i></a></div><x-attempt-table :attempts="$recent"/></section>
@endsection
