@extends('layouts.app')
@section('title',__('ui.practice'))
@section('main-class','practice-main')
@section('content')
@php($config = ['answers'=>(object)$attempt->answers,'remaining'=>max(0,(int)ceil(now()->diffInSeconds($attempt->ends_at,false))),'answerUrl'=>route('practice.answer',$attempt),'statusUrl'=>route('practice.status',$attempt),'submitUrl'=>route('practice.submit',$attempt),'resultUrl'=>route('practice.result',$attempt),'questions'=>$questions->pluck('id')->all()])
<script type="application/json" id="practice-config">{!! json_encode($config, JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) !!}</script>
<div x-data="practiceSession" class="practice-workspace" @if($attempt->snapshot['copy_protection']) data-copy-protected @endif>
    <div class="practice-top"><div><span class="eyebrow">{{ $attempt->snapshot['module'] }}</span><h1>{{ $attempt->snapshot['title'] }}</h1></div><div class="timer" :class="{'urgent':remaining<=60}" role="timer" aria-label="{{ __('ui.remaining') }}"><i data-lucide="timer"></i><div><small>{{ __('ui.remaining') }}</small><strong x-text="clock"></strong></div></div></div>
    <div class="practice-save-strip" aria-live="polite"><span :class="{'text-danger':error}"><i data-lucide="cloud-check"></i><span x-show="!error && !pendingCount">{{ __('ui.saved_answers') }}</span><span x-show="!error && pendingCount" x-cloak>{{ __('ui.saving') }}</span><span x-show="error" x-cloak>{{ __('ui.save_error') }}</span></span><span><b x-text="Object.keys(answers).length"></b> / {{ $questions->count() }} {{ __('ui.answered') }}</span></div>
    <div class="practice-columns"><div class="question-list">
    @foreach($questions as $q)
        <section class="question-block" id="question-{{ $q['id'] }}"><div class="question-heading"><span class="eyebrow">{{ __('ui.question') }} {{ $loop->iteration }} / {{ $questions->count() }}</span><span class="answered-mark" x-show="answers[{{ $q['id'] }}]" x-cloak><i data-lucide="check"></i>{{ __('ui.answered') }}</span></div><h2>{{ $q['question'] }}</h2><fieldset :disabled="finished || remaining<=0"><legend class="sr-only">{{ $q['question'] }}</legend>
        @foreach(['A','B','C','D'] as $letter)<label class="answer-option" :class="{'chosen':answers[{{ $q['id'] }}]==='{{ $letter }}'}"><input type="radio" name="question_{{ $q['id'] }}" value="{{ $letter }}" :checked="answers[{{ $q['id'] }}]==='{{ $letter }}'" @change="choose({{ $q['id'] }},'{{ $letter }}')"><span class="option-letter">{{ $letter }}</span><span>{{ $q['option_'.strtolower($letter)] }}</span><i data-lucide="circle-check" class="option-check"></i></label>@endforeach
        </fieldset><div class="question-controls">@if(!$loop->first)<button class="text-link" @click="go({{ $questions[$loop->index-1]['id'] }})"><i data-lucide="arrow-left"></i>{{ __('ui.previous') }}</button>@else<span></span>@endif @if(!$loop->last)<button class="text-link" @click="go({{ $questions[$loop->index+1]['id'] }})">{{ __('ui.next') }}<i data-lucide="arrow-right"></i></button>@else<button class="text-link" @click="confirmOpen=true">{{ __('ui.submit') }}<i data-lucide="check"></i></button>@endif</div></section>
    @endforeach
    </div><aside class="question-sidebar"><h2>{{ __('ui.questions') }}</h2><div class="question-grid">@foreach($questions as $q)<button :class="{'done':answers[{{ $q['id'] }}]}" @click="go({{ $q['id'] }})" aria-label="{{ __('ui.question') }} {{ $loop->iteration }}">{{ $loop->iteration }}</button>@endforeach</div><div class="question-legend"><span><b class="legend-box filled"></b>{{ __('ui.answered') }}</span><span><b class="legend-box"></b>{{ __('ui.unanswered') }}</span></div><button class="button primary full" @click="confirmOpen=true" :disabled="finished || remaining<=0">{{ __('ui.submit') }}<i data-lucide="check"></i></button><p class="text-danger" x-show="submitError" x-cloak>{{ __('ui.finish_error') }}</p></aside></div>
    <div class="modal-backdrop" x-show="confirmOpen" x-cloak @keydown.escape.window="confirmOpen=false"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="submit-title"><span class="item-icon blue"><i data-lucide="send"></i></span><h2 id="submit-title">{{ __('ui.submit_title') }}</h2><p>{{ __('ui.submit_note') }}</p><div class="confirm-count"><strong x-text="Object.keys(answers).length"></strong> / {{ $questions->count() }} {{ __('ui.answered') }}<span><b x-text="{{ $questions->count() }}-Object.keys(answers).length"></b> {{ __('ui.unanswered') }}</span></div><div class="form-actions"><button class="button secondary" @click="confirmOpen=false">{{ __('ui.cancel') }}</button><button class="button primary" @click="finish(false)" :disabled="submitting || pendingCount>0">{{ __('ui.confirm_submit') }}<i data-lucide="arrow-right"></i></button></div></section></div>
</div>
@endsection


