@extends('layouts.app')
@section('title',__('ui.'.$kind))
@section('content')
<a class="back-link" href="{{ route('admin.content.index',$kind) }}"><i data-lucide="arrow-left"></i>{{ __('ui.'.$kind) }}</a>
<x-page-heading :title="($item->exists?__('ui.edit'):__('ui.add')).' · '.__('ui.'.$kind)"/>
<form class="editor-form" method="POST" action="{{ $item->exists?route('admin.content.update',[$kind,$item->id]):route('admin.content.store',$kind) }}">@csrf @if($item->exists)@method('PUT')@endif
<div class="editor-main stack-form">
@if($kind==='modules')<label>{{ __('ui.program') }}<select name="program_id" required><option value="">—</option>@foreach($programs as $p)<option value="{{ $p->id }}" @selected(old('program_id',$item->program_id)==$p->id)>{{ $p->title }}</option>@endforeach</select></label>@endif
@if(in_array($kind,['packages','materials']))<label>{{ __('ui.module') }}<select name="module_id" required><option value="">—</option>@foreach($modules as $m)<option value="{{ $m->id }}" @selected(old('module_id',$item->module_id)==$m->id)>{{ $m->program->title }} / {{ $m->title }}</option>@endforeach</select></label>@endif
@if($kind==='questions')<label>{{ __('ui.package') }}<select name="practice_package_id" required><option value="">—</option>@foreach($packages as $p)<option value="{{ $p->id }}" @selected(old('practice_package_id',$item->practice_package_id)==$p->id)>{{ $p->module->program->title }} / {{ $p->module->title }} / {{ $p->title }}</option>@endforeach</select></label><label>{{ __('ui.question') }}<textarea name="question" rows="4" required maxlength="10000">{{ old('question',$item->question) }}</textarea></label><div class="option-input-grid">@foreach(['a','b','c','d'] as $letter)<label>{{ __('ui.option') }} {{ strtoupper($letter) }}<textarea name="option_{{ $letter }}" rows="2" required maxlength="2000">{{ old('option_'.$letter,$item->{'option_'.$letter}) }}</textarea></label>@endforeach</div><label>{{ __('ui.correct_answer') }}<select name="correct_answer" required>@foreach(['A','B','C','D'] as $letter)<option value="{{ $letter }}" @selected(old('correct_answer',$item->correct_answer)===$letter)>{{ $letter }}</option>@endforeach</select></label><label>{{ __('ui.explanation') }}<textarea name="explanation" rows="4" maxlength="10000">{{ old('explanation',$item->explanation) }}</textarea></label>
@else<label>{{ __('ui.title') }}<input name="title" value="{{ old('title',$item->title) }}" required maxlength="180"></label>@endif
@if(in_array($kind,['programs','modules','packages']))<label>{{ __('ui.description') }}<textarea name="description" rows="4" maxlength="3000">{{ old('description',$item->description) }}</textarea></label>@endif
@if($kind==='materials')<div class="material-editor" x-data="materialEditor"><label for="material-content">{{ __('ui.content') }}</label><div class="editor-toolbar"><div><button type="button" class="icon-button" @click="wrap('**')" title="{{ __('ui.bold') }}" aria-label="{{ __('ui.bold') }}"><i data-lucide="bold"></i></button><button type="button" class="icon-button" @click="wrap('*')" title="{{ __('ui.italic') }}" aria-label="{{ __('ui.italic') }}"><i data-lucide="italic"></i></button><button type="button" class="icon-button" @click="prefix('## ')" title="{{ __('ui.heading') }}" aria-label="{{ __('ui.heading') }}"><i data-lucide="heading-2"></i></button><button type="button" class="icon-button" @click="prefix('- ')" title="{{ __('ui.bullet_list') }}" aria-label="{{ __('ui.bullet_list') }}"><i data-lucide="list"></i></button></div><div class="segmented"><button type="button" :class="{'selected':!preview}" @click="preview=false">{{ __('ui.write') }}</button><button type="button" :class="{'selected':preview}" @click="render()">{{ __('ui.preview') }}</button></div></div><textarea id="material-content" name="content" x-ref="input" rows="18" x-show="!preview" required>{{ old('content',$item->content) }}</textarea><div class="prose-content material-preview" x-show="preview" x-cloak x-html="html"></div></div>@endif
</div><aside class="editor-aside stack-form"><label>{{ __('ui.status') }}<select name="status">@foreach(['draft','active','archived'] as $status)<option value="{{ $status }}" @selected(old('status',$item->status??'draft')===$status)>{{ __('ui.'.$status) }}</option>@endforeach</select></label>
@if($kind==='programs')<fieldset class="cover-picker"><legend>{{ __('ui.cover') }}</legend>@foreach(['japanese','english','workplace'] as $cover)<label><input type="radio" name="cover" value="{{ $cover }}" @checked(old('cover',$item->cover??'japanese')===$cover)><img src="{{ asset('images/'.$cover.'.jpg') }}" alt="{{ __('ui.'.$cover) }}"><span>{{ __('ui.'.$cover) }}</span></label>@endforeach</fieldset>@endif
@if($kind==='packages')<label>{{ __('ui.duration_minutes') }}<input name="duration_minutes" type="number" min="1" max="240" value="{{ old('duration_minutes',$item->duration_minutes??20) }}" required></label><label>{{ __('ui.passing_score') }} (%)<input name="passing_score" type="number" min="0" max="100" value="{{ old('passing_score',$item->passing_score??70) }}" required></label>@foreach(['show_explanations'=>true,'copy_protection'=>false] as $field=>$default)<input type="hidden" name="{{ $field }}" value="0"><label class="checkbox-label"><input type="checkbox" name="{{ $field }}" value="1" @checked(old($field,$item->{$field}??$default))>{{ __('ui.'.$field) }}</label>@endforeach @endif
@if($kind==='materials')<label>{{ __('ui.reading_time') }} ({{ __('ui.min') }})<input type="number" name="reading_minutes" min="1" max="240" value="{{ old('reading_minutes',$item->reading_minutes??5) }}" required></label>@endif
<button class="button primary full" type="submit"><i data-lucide="save"></i>{{ __('ui.save') }}</button></aside></form>
@endsection
